### ISSUE TITLE
Rename to ci.lbs

### ISSUE THREAD

**Issue by barkingfoodog** [omnis-ci/ci.lbs#2]
When I split this library out to its own project I settled on naming it `ci.lbs` instead of `omnisci`. This helps distinguish it from the overall `omnis.ci` project.

However, the library was never renamed to match and is still deployed as `omnisci.lbs`. I'd like to rename the library to `ci.lbs`. @teneruffian I know you're using this library. Would this rename be a breaking change for you?

**Comment by teneruffian** [comment]
This proposed change makes sense to me and will not adversely affect my use.

**Comment by barkingfoodog** [comment]
Excellent. I've made the change.
